apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: demo-llm-route
  namespace: agentgateway-system
spec:
  hostnames:
  - demo-llm.example.com
  parentRefs:
  - name: https
  rules:
  - backendRefs:
    - group: agentgateway.dev
      kind: AgentgatewayBackend
      name: openai-llm
